// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiHN-mmUT2jP8NTMKqS2s_I7JvpFwlvmY',
    appId: '1:284117889308:web:cccec1a2d87bff18a00ad9',
    messagingSenderId: '284117889308',
    projectId: 'foodys-7b4be',
    authDomain: 'foodys-7b4be.firebaseapp.com',
    storageBucket: 'foodys-7b4be.appspot.com',
    measurementId: 'G-HXWJNQN63B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuyjoBnXvLRq9QKeCFiXPoQgp1-gD9MtU',
    appId: '1:284117889308:android:2c0af06b4ca934aaa00ad9',
    messagingSenderId: '284117889308',
    projectId: 'foodys-7b4be',
    storageBucket: 'foodys-7b4be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtwMMFoXRjyPnjBAlDyS_ruXufdPmRgBI',
    appId: '1:284117889308:ios:e051e4fe8bd9935aa00ad9',
    messagingSenderId: '284117889308',
    projectId: 'foodys-7b4be',
    storageBucket: 'foodys-7b4be.appspot.com',
    iosBundleId: 'com.example.foodys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtwMMFoXRjyPnjBAlDyS_ruXufdPmRgBI',
    appId: '1:284117889308:ios:e051e4fe8bd9935aa00ad9',
    messagingSenderId: '284117889308',
    projectId: 'foodys-7b4be',
    storageBucket: 'foodys-7b4be.appspot.com',
    iosBundleId: 'com.example.foodys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiHN-mmUT2jP8NTMKqS2s_I7JvpFwlvmY',
    appId: '1:284117889308:web:9238a7e91ea2fea3a00ad9',
    messagingSenderId: '284117889308',
    projectId: 'foodys-7b4be',
    authDomain: 'foodys-7b4be.firebaseapp.com',
    storageBucket: 'foodys-7b4be.appspot.com',
    measurementId: 'G-2SKGNLJZTP',
  );
}
